GET https://blooming-sierra-17635.herokuapp.com/flower/all

###
POST https://blooming-sierra-17635.herokuapp.com/flower/add
Content-Type: application/json

{
  "petal": 3.00,
  "color": "ma",
  "price": 2.00
}